/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  BalanceTransactionsApi,
  CampaignsApi,
  FieldsApi,
  FundingSourcesApi,
  InvoicesApi,
  MembersApi,
  OrdersApi,
  OrganizationsApi,
  ProductsApi,
  RewardsApi,
  WebhooksApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { TremendousCustom } from "./client-custom";

export class Tremendous extends TremendousCustom {
  readonly balanceTransactions: BalanceTransactionsApi;
  readonly campaigns: CampaignsApi;
  readonly fields: FieldsApi;
  readonly fundingSources: FundingSourcesApi;
  readonly invoices: InvoicesApi;
  readonly members: MembersApi;
  readonly orders: OrdersApi;
  readonly organizations: OrganizationsApi;
  readonly products: ProductsApi;
  readonly rewards: RewardsApi;
  readonly webhooks: WebhooksApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.balanceTransactions = new BalanceTransactionsApi(configuration);
    this.campaigns = new CampaignsApi(configuration);
    this.fields = new FieldsApi(configuration);
    this.fundingSources = new FundingSourcesApi(configuration);
    this.invoices = new InvoicesApi(configuration);
    this.members = new MembersApi(configuration);
    this.orders = new OrdersApi(configuration);
    this.organizations = new OrganizationsApi(configuration);
    this.products = new ProductsApi(configuration);
    this.rewards = new RewardsApi(configuration);
    this.webhooks = new WebhooksApi(configuration);
  }

}
