/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BalanceTransactionsListAll422ResponseErrors } from './balance-transactions-list-all422-response-errors';

/**
 * 
 * @export
 * @interface BalanceTransactionsListAll422Response
 */
export interface BalanceTransactionsListAll422Response {
    /**
     * 
     * @type {BalanceTransactionsListAll422ResponseErrors}
     * @memberof BalanceTransactionsListAll422Response
     */
    'errors': BalanceTransactionsListAll422ResponseErrors;
}

