/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A list of the settings that you wish to copy over to the new organization.
 * @export
 * @interface CreateOrganizationCopySettings
 */
export interface CreateOrganizationCopySettings {
    /**
     * Copy over the campaigns from the current organization to the new organization. Defaults to `false`.
     * @type {boolean}
     * @memberof CreateOrganizationCopySettings
     */
    'campaigns'?: boolean;
    /**
     * Copy over the custom fields from the current organization to the new organization. Defaults to `false`.
     * @type {boolean}
     * @memberof CreateOrganizationCopySettings
     */
    'custom_fields'?: boolean;
    /**
     * Copy over the order approvals settings from the current organization to the new organization. Defaults to `false`.
     * @type {boolean}
     * @memberof CreateOrganizationCopySettings
     */
    'order_approvals'?: boolean;
    /**
     * Copy over the payment methods from the current organization to the new organization. Defaults to `false`.
     * @type {boolean}
     * @memberof CreateOrganizationCopySettings
     */
    'payment_methods'?: boolean;
    /**
     * Copy over the security settings from the current organization to the new organization. Defaults to `true`.
     * @type {boolean}
     * @memberof CreateOrganizationCopySettings
     */
    'security_settings'?: boolean;
    /**
     * Copy over the users from the current organization to the new organization. Defaults to `false`.
     * @type {boolean}
     * @memberof CreateOrganizationCopySettings
     */
    'users'?: boolean;
}

