/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CreateMember
 */
export interface CreateMember {
    /**
     * Email address of the member
     * @type {string}
     * @memberof CreateMember
     */
    'email': string;
    /**
     * Full name of the member
     * @type {string}
     * @memberof CreateMember
     */
    'name': string;
    /**
     * Role of the member within the organization.  <table>   <thead>     <tr>       <th>Role</th>       <th>Description</th>     </tr>   </thead>     <tr>       <td><code>MEMBER</code></td>       <td>Limited permissions. Can view their own reward and order histories only.</td>     </tr>     <tr>       <td><code>ADMIN</code></td>       <td>Update organization settings, invite other members to the organization, and view all member order and reward histories within their organization.</td>     </tr>   <tbody> </table> 
     * @type {string}
     * @memberof CreateMember
     */
    'role': CreateMemberRoleEnum;
}

type CreateMemberRoleEnum = 'MEMBER' | 'ADMIN'


