/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FundingSourcesGetById429ResponseErrors } from './funding-sources-get-by-id429-response-errors';

/**
 * 
 * @export
 * @interface FundingSourcesGetById429Response
 */
export interface FundingSourcesGetById429Response {
    /**
     * 
     * @type {FundingSourcesGetById429ResponseErrors}
     * @memberof FundingSourcesGetById429Response
     */
    'errors': FundingSourcesGetById429ResponseErrors;
}

