/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface FundingSourcesGetById429ResponseErrors
 */
export interface FundingSourcesGetById429ResponseErrors {
    /**
     * Error message
     * @type {string}
     * @memberof FundingSourcesGetById429ResponseErrors
     */
    'message'?: string;
    /**
     * Mirrors the request parameters structure, filled only with the (nested) properties that caused an error.
     * @type {object}
     * @memberof FundingSourcesGetById429ResponseErrors
     */
    'payload'?: object;
}

