/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InvoicesCreateAndFundAccountBalance400ResponseErrors } from './invoices-create-and-fund-account-balance400-response-errors';

/**
 * 
 * @export
 * @interface InvoicesCreateAndFundAccountBalance400Response
 */
export interface InvoicesCreateAndFundAccountBalance400Response {
    /**
     * 
     * @type {InvoicesCreateAndFundAccountBalance400ResponseErrors}
     * @memberof InvoicesCreateAndFundAccountBalance400Response
     */
    'errors': InvoicesCreateAndFundAccountBalance400ResponseErrors;
}

