/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InvoicesGetAllResponseInvoicesInner } from './invoices-get-all-response-invoices-inner';

/**
 * 
 * @export
 * @interface InvoicesGetAllResponse
 */
export interface InvoicesGetAllResponse {
    /**
     * 
     * @type {Array<InvoicesGetAllResponseInvoicesInner>}
     * @memberof InvoicesGetAllResponse
     */
    'invoices': Array<InvoicesGetAllResponseInvoicesInner>;
    /**
     * The total number of invoices across all pages
     * @type {number}
     * @memberof InvoicesGetAllResponse
     */
    'total_count': number;
}

