/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MembersGetMember500ResponseErrors } from './members-get-member500-response-errors';

/**
 * 
 * @export
 * @interface MembersGetMember500Response
 */
export interface MembersGetMember500Response {
    /**
     * 
     * @type {MembersGetMember500ResponseErrors}
     * @memberof MembersGetMember500Response
     */
    'errors': MembersGetMember500ResponseErrors;
}

