/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MembersListMembers429ResponseErrors } from './members-list-members429-response-errors';

/**
 * 
 * @export
 * @interface MembersListMembers429Response
 */
export interface MembersListMembers429Response {
    /**
     * 
     * @type {MembersListMembers429ResponseErrors}
     * @memberof MembersListMembers429Response
     */
    'errors': MembersListMembers429ResponseErrors;
}

