/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MembersCreateNewMember400ResponseErrors } from './members-create-new-member400-response-errors';

/**
 * 
 * @export
 * @interface MembersCreateNewMember400Response
 */
export interface MembersCreateNewMember400Response {
    /**
     * 
     * @type {MembersCreateNewMember400ResponseErrors}
     * @memberof MembersCreateNewMember400Response
     */
    'errors': MembersCreateNewMember400ResponseErrors;
}

