/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrdersApproveOrderById403ResponseErrors } from './orders-approve-order-by-id403-response-errors';

/**
 * 
 * @export
 * @interface OrdersApproveOrderById403Response
 */
export interface OrdersApproveOrderById403Response {
    /**
     * 
     * @type {OrdersApproveOrderById403ResponseErrors}
     * @memberof OrdersApproveOrderById403Response
     */
    'errors': OrdersApproveOrderById403ResponseErrors;
}

