/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrdersCreateOrderResponseOrderRewardsInnerCustomFieldsInner } from './orders-create-order-response-order-rewards-inner-custom-fields-inner';
import { OrdersCreateOrderResponseOrderRewardsInnerDelivery } from './orders-create-order-response-order-rewards-inner-delivery';
import { OrdersCreateOrderResponseOrderRewardsInnerRecipient } from './orders-create-order-response-order-rewards-inner-recipient';
import { OrdersCreateOrderResponseOrderRewardsInnerValue } from './orders-create-order-response-order-rewards-inner-value';

/**
 * A single reward, sent to a recipient. A reward is always part of an order.  Either `products` or `campaign_id` must be specified. 
 * @export
 * @interface OrdersCreateOrderResponseOrderRewardsInner
 */
export interface OrdersCreateOrderResponseOrderRewardsInner {
    /**
     * Tremendous ID of the reward
     * @type {string}
     * @memberof OrdersCreateOrderResponseOrderRewardsInner
     */
    'id'?: string;
    /**
     * Tremendous ID of the order this reward is part of.
     * @type {string}
     * @memberof OrdersCreateOrderResponseOrderRewardsInner
     */
    'order_id'?: string;
    /**
     * Date the reward was created
     * @type {string}
     * @memberof OrdersCreateOrderResponseOrderRewardsInner
     */
    'created_at'?: string;
    /**
     * 
     * @type {OrdersCreateOrderResponseOrderRewardsInnerValue}
     * @memberof OrdersCreateOrderResponseOrderRewardsInner
     */
    'value'?: OrdersCreateOrderResponseOrderRewardsInnerValue;
    /**
     * 
     * @type {OrdersCreateOrderResponseOrderRewardsInnerRecipient}
     * @memberof OrdersCreateOrderResponseOrderRewardsInner
     */
    'recipient'?: OrdersCreateOrderResponseOrderRewardsInnerRecipient;
    /**
     * Timestamp of reward delivery within the next year. Note that if date-time is provided, the time values will be ignored.
     * @type {string}
     * @memberof OrdersCreateOrderResponseOrderRewardsInner
     */
    'deliver_at'?: string;
    /**
     * 
     * @type {Array<OrdersCreateOrderResponseOrderRewardsInnerCustomFieldsInner>}
     * @memberof OrdersCreateOrderResponseOrderRewardsInner
     */
    'custom_fields'?: Array<OrdersCreateOrderResponseOrderRewardsInnerCustomFieldsInner>;
    /**
     * 
     * @type {OrdersCreateOrderResponseOrderRewardsInnerDelivery}
     * @memberof OrdersCreateOrderResponseOrderRewardsInner
     */
    'delivery'?: OrdersCreateOrderResponseOrderRewardsInnerDelivery;
}

