/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrdersGetListResponseOrdersInnerRewardCustomFieldsInner } from './orders-get-list-response-orders-inner-reward-custom-fields-inner';
import { OrdersGetListResponseOrdersInnerRewardRecipient } from './orders-get-list-response-orders-inner-reward-recipient';
import { OrdersGetListResponseOrdersInnerRewardValue } from './orders-get-list-response-orders-inner-reward-value';
import { RewardsListAllRewardsResponseRewardsInnerDelivery } from './rewards-list-all-rewards-response-rewards-inner-delivery';

/**
 * A single reward, sent to a recipient. A reward is always part of an order.  Either `products` or `campaign_id` must be specified. 
 * @export
 * @interface OrdersGetListResponseOrdersInnerReward
 */
export interface OrdersGetListResponseOrdersInnerReward {
    /**
     * Tremendous ID of the reward
     * @type {string}
     * @memberof OrdersGetListResponseOrdersInnerReward
     */
    'id'?: string;
    /**
     * Tremendous ID of the order this reward is part of.
     * @type {string}
     * @memberof OrdersGetListResponseOrdersInnerReward
     */
    'order_id'?: string;
    /**
     * Date the reward was created
     * @type {string}
     * @memberof OrdersGetListResponseOrdersInnerReward
     */
    'created_at'?: string;
    /**
     * 
     * @type {OrdersGetListResponseOrdersInnerRewardValue}
     * @memberof OrdersGetListResponseOrdersInnerReward
     */
    'value'?: OrdersGetListResponseOrdersInnerRewardValue;
    /**
     * 
     * @type {OrdersGetListResponseOrdersInnerRewardRecipient}
     * @memberof OrdersGetListResponseOrdersInnerReward
     */
    'recipient'?: OrdersGetListResponseOrdersInnerRewardRecipient;
    /**
     * Timestamp of reward delivery within the next year. Note that if date-time is provided, the time values will be ignored.
     * @type {string}
     * @memberof OrdersGetListResponseOrdersInnerReward
     */
    'deliver_at'?: string;
    /**
     * 
     * @type {Array<OrdersGetListResponseOrdersInnerRewardCustomFieldsInner>}
     * @memberof OrdersGetListResponseOrdersInnerReward
     */
    'custom_fields'?: Array<OrdersGetListResponseOrdersInnerRewardCustomFieldsInner>;
    /**
     * 
     * @type {RewardsListAllRewardsResponseRewardsInnerDelivery}
     * @memberof OrdersGetListResponseOrdersInnerReward
     */
    'delivery'?: RewardsListAllRewardsResponseRewardsInnerDelivery;
}

