/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrdersCreateOrder201ResponseOrderRewardCustomFieldsInner } from './orders-create-order201-response-order-reward-custom-fields-inner';
import { OrdersCreateOrder201ResponseOrderRewardRecipient } from './orders-create-order201-response-order-reward-recipient';
import { OrdersCreateOrder201ResponseOrderRewardValue } from './orders-create-order201-response-order-reward-value';
import { RewardsListAllRewardsResponseRewardsInnerDelivery } from './rewards-list-all-rewards-response-rewards-inner-delivery';

/**
 * A single reward, sent to a recipient. A reward is always part of an order.  Either `products` or `campaign_id` must be specified. 
 * @export
 * @interface OrdersCreateOrder201ResponseOrderReward
 */
export interface OrdersCreateOrder201ResponseOrderReward {
    /**
     * Tremendous ID of the reward
     * @type {string}
     * @memberof OrdersCreateOrder201ResponseOrderReward
     */
    'id'?: string;
    /**
     * Tremendous ID of the order this reward is part of.
     * @type {string}
     * @memberof OrdersCreateOrder201ResponseOrderReward
     */
    'order_id'?: string;
    /**
     * Date the reward was created
     * @type {string}
     * @memberof OrdersCreateOrder201ResponseOrderReward
     */
    'created_at'?: string;
    /**
     * 
     * @type {OrdersCreateOrder201ResponseOrderRewardValue}
     * @memberof OrdersCreateOrder201ResponseOrderReward
     */
    'value'?: OrdersCreateOrder201ResponseOrderRewardValue;
    /**
     * 
     * @type {OrdersCreateOrder201ResponseOrderRewardRecipient}
     * @memberof OrdersCreateOrder201ResponseOrderReward
     */
    'recipient'?: OrdersCreateOrder201ResponseOrderRewardRecipient;
    /**
     * Timestamp of reward delivery within the next year. Note that if date-time is provided, the time values will be ignored.
     * @type {string}
     * @memberof OrdersCreateOrder201ResponseOrderReward
     */
    'deliver_at'?: string;
    /**
     * 
     * @type {Array<OrdersCreateOrder201ResponseOrderRewardCustomFieldsInner>}
     * @memberof OrdersCreateOrder201ResponseOrderReward
     */
    'custom_fields'?: Array<OrdersCreateOrder201ResponseOrderRewardCustomFieldsInner>;
    /**
     * 
     * @type {RewardsListAllRewardsResponseRewardsInnerDelivery}
     * @memberof OrdersCreateOrder201ResponseOrderReward
     */
    'delivery'?: RewardsListAllRewardsResponseRewardsInnerDelivery;
}

