/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrdersRejectByIdResponseOrderPaymentRefund } from './orders-reject-by-id-response-order-payment-refund';

/**
 * Cost breakdown of the order (cost of rewards + fees). Cost and fees are always denominated in USD, independent from the currency of the ordered rewards. Note that this property will only appear for processed orders (`status` is `EXECUTED`).
 * @export
 * @interface OrdersRejectByIdResponseOrderPayment
 */
export interface OrdersRejectByIdResponseOrderPayment {
    /**
     * Total price of the order before fees (in USD)
     * @type {number}
     * @memberof OrdersRejectByIdResponseOrderPayment
     */
    'subtotal'?: number;
    /**
     * Total price of the order including fees (in USD)
     * @type {number}
     * @memberof OrdersRejectByIdResponseOrderPayment
     */
    'total'?: number;
    /**
     * Fees for the order (in USD)
     * @type {number}
     * @memberof OrdersRejectByIdResponseOrderPayment
     */
    'fees'?: number;
    /**
     * 
     * @type {OrdersRejectByIdResponseOrderPaymentRefund}
     * @memberof OrdersRejectByIdResponseOrderPayment
     */
    'refund'?: OrdersRejectByIdResponseOrderPaymentRefund;
    /**
     * Name of the channel in which the order was created
     * @type {string}
     * @memberof OrdersRejectByIdResponseOrderPayment
     */
    'channel'?: OrdersRejectByIdResponseOrderPaymentChannelEnum;
}

type OrdersRejectByIdResponseOrderPaymentChannelEnum = 'UI' | 'API' | 'EMBED' | 'DECIPHER' | 'QUALTRICS' | 'TYPEFORM' | 'SURVEY MONKEY'


