/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrdersRejectByIdResponseOrderRewardCustomFieldsInner } from './orders-reject-by-id-response-order-reward-custom-fields-inner';
import { OrdersRejectByIdResponseOrderRewardRecipient } from './orders-reject-by-id-response-order-reward-recipient';
import { OrdersRejectByIdResponseOrderRewardValue } from './orders-reject-by-id-response-order-reward-value';
import { RewardsListAllRewardsResponseRewardsInnerDelivery } from './rewards-list-all-rewards-response-rewards-inner-delivery';

/**
 * A single reward, sent to a recipient. A reward is always part of an order.  Either `products` or `campaign_id` must be specified. 
 * @export
 * @interface OrdersRejectByIdResponseOrderReward
 */
export interface OrdersRejectByIdResponseOrderReward {
    /**
     * Tremendous ID of the reward
     * @type {string}
     * @memberof OrdersRejectByIdResponseOrderReward
     */
    'id'?: string;
    /**
     * Tremendous ID of the order this reward is part of.
     * @type {string}
     * @memberof OrdersRejectByIdResponseOrderReward
     */
    'order_id'?: string;
    /**
     * Date the reward was created
     * @type {string}
     * @memberof OrdersRejectByIdResponseOrderReward
     */
    'created_at'?: string;
    /**
     * 
     * @type {OrdersRejectByIdResponseOrderRewardValue}
     * @memberof OrdersRejectByIdResponseOrderReward
     */
    'value'?: OrdersRejectByIdResponseOrderRewardValue;
    /**
     * 
     * @type {OrdersRejectByIdResponseOrderRewardRecipient}
     * @memberof OrdersRejectByIdResponseOrderReward
     */
    'recipient'?: OrdersRejectByIdResponseOrderRewardRecipient;
    /**
     * Timestamp of reward delivery within the next year. Note that if date-time is provided, the time values will be ignored.
     * @type {string}
     * @memberof OrdersRejectByIdResponseOrderReward
     */
    'deliver_at'?: string;
    /**
     * 
     * @type {Array<OrdersRejectByIdResponseOrderRewardCustomFieldsInner>}
     * @memberof OrdersRejectByIdResponseOrderReward
     */
    'custom_fields'?: Array<OrdersRejectByIdResponseOrderRewardCustomFieldsInner>;
    /**
     * 
     * @type {RewardsListAllRewardsResponseRewardsInnerDelivery}
     * @memberof OrdersRejectByIdResponseOrderReward
     */
    'delivery'?: RewardsListAllRewardsResponseRewardsInnerDelivery;
}

