/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrdersCreateOrder202ResponseOrderRewardsInnerCustomFieldsInner } from './orders-create-order202-response-order-rewards-inner-custom-fields-inner';
import { OrdersCreateOrder202ResponseOrderRewardsInnerDelivery } from './orders-create-order202-response-order-rewards-inner-delivery';
import { OrdersCreateOrder202ResponseOrderRewardsInnerRecipient } from './orders-create-order202-response-order-rewards-inner-recipient';
import { OrdersCreateOrder202ResponseOrderRewardsInnerValue } from './orders-create-order202-response-order-rewards-inner-value';

/**
 * A single reward, sent to a recipient. A reward is always part of an order.  Either `products` or `campaign_id` must be specified. 
 * @export
 * @interface OrdersCreateOrder202ResponseOrderRewardsInner
 */
export interface OrdersCreateOrder202ResponseOrderRewardsInner {
    /**
     * Tremendous ID of the reward
     * @type {string}
     * @memberof OrdersCreateOrder202ResponseOrderRewardsInner
     */
    'id'?: string;
    /**
     * Tremendous ID of the order this reward is part of.
     * @type {string}
     * @memberof OrdersCreateOrder202ResponseOrderRewardsInner
     */
    'order_id'?: string;
    /**
     * Date the reward was created
     * @type {string}
     * @memberof OrdersCreateOrder202ResponseOrderRewardsInner
     */
    'created_at'?: string;
    /**
     * 
     * @type {OrdersCreateOrder202ResponseOrderRewardsInnerValue}
     * @memberof OrdersCreateOrder202ResponseOrderRewardsInner
     */
    'value'?: OrdersCreateOrder202ResponseOrderRewardsInnerValue;
    /**
     * 
     * @type {OrdersCreateOrder202ResponseOrderRewardsInnerRecipient}
     * @memberof OrdersCreateOrder202ResponseOrderRewardsInner
     */
    'recipient'?: OrdersCreateOrder202ResponseOrderRewardsInnerRecipient;
    /**
     * Timestamp of reward delivery within the next year. Note that if date-time is provided, the time values will be ignored.
     * @type {string}
     * @memberof OrdersCreateOrder202ResponseOrderRewardsInner
     */
    'deliver_at'?: string;
    /**
     * 
     * @type {Array<OrdersCreateOrder202ResponseOrderRewardsInnerCustomFieldsInner>}
     * @memberof OrdersCreateOrder202ResponseOrderRewardsInner
     */
    'custom_fields'?: Array<OrdersCreateOrder202ResponseOrderRewardsInnerCustomFieldsInner>;
    /**
     * 
     * @type {OrdersCreateOrder202ResponseOrderRewardsInnerDelivery}
     * @memberof OrdersCreateOrder202ResponseOrderRewardsInner
     */
    'delivery'?: OrdersCreateOrder202ResponseOrderRewardsInnerDelivery;
}

