/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrdersApproveOrderById422ResponseErrors } from './orders-approve-order-by-id422-response-errors';

/**
 * 
 * @export
 * @interface OrdersApproveOrderById422Response
 */
export interface OrdersApproveOrderById422Response {
    /**
     * 
     * @type {OrdersApproveOrderById422ResponseErrors}
     * @memberof OrdersApproveOrderById422Response
     */
    'errors': OrdersApproveOrderById422ResponseErrors;
}

