/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrganizationsCreateApiKey404ResponseErrors } from './organizations-create-api-key404-response-errors';

/**
 * 
 * @export
 * @interface OrganizationsCreateApiKey404Response
 */
export interface OrganizationsCreateApiKey404Response {
    /**
     * 
     * @type {OrganizationsCreateApiKey404ResponseErrors}
     * @memberof OrganizationsCreateApiKey404Response
     */
    'errors': OrganizationsCreateApiKey404ResponseErrors;
}

