/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { OrganizationsCreateNewOrganizationRequestCopySettings } from './organizations-create-new-organization-request-copy-settings';

/**
 * 
 * @export
 * @interface OrganizationsCreateNewOrganizationRequest
 */
export interface OrganizationsCreateNewOrganizationRequest {
    /**
     * Name of the organization
     * @type {string}
     * @memberof OrganizationsCreateNewOrganizationRequest
     */
    'name': string;
    /**
     * URL of the website of that organization
     * @type {string}
     * @memberof OrganizationsCreateNewOrganizationRequest
     */
    'website': string;
    /**
     * Default value is `false`. Set to true to also generate an API key associated to the new organization.
     * @type {boolean}
     * @memberof OrganizationsCreateNewOrganizationRequest
     */
    'with_api_key'?: boolean;
    /**
     * 
     * @type {OrganizationsCreateNewOrganizationRequestCopySettings}
     * @memberof OrganizationsCreateNewOrganizationRequest
     */
    'copy_settings'?: OrganizationsCreateNewOrganizationRequestCopySettings;
    /**
     * Phone number of the organization. For non-US phone numbers, specify the country code (prefixed with +).
     * @type {string}
     * @memberof OrganizationsCreateNewOrganizationRequest
     */
    'phone'?: string;
}

