/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentDetailsRefund } from './payment-details-refund';

/**
 * 
 * @export
 * @interface PaymentDetails
 */
export interface PaymentDetails {
    /**
     * Total price of the order before fees (in USD)
     * @type {number}
     * @memberof PaymentDetails
     */
    'subtotal'?: number;
    /**
     * Total price of the order including fees (in USD)
     * @type {number}
     * @memberof PaymentDetails
     */
    'total'?: number;
    /**
     * Fees for the order (in USD)
     * @type {number}
     * @memberof PaymentDetails
     */
    'fees'?: number;
    /**
     * 
     * @type {PaymentDetailsRefund}
     * @memberof PaymentDetails
     */
    'refund'?: PaymentDetailsRefund;
    /**
     * Name of the channel in which the order was created
     * @type {string}
     * @memberof PaymentDetails
     */
    'channel'?: PaymentDetailsChannelEnum;
}

type PaymentDetailsChannelEnum = 'UI' | 'API' | 'EMBED' | 'DECIPHER' | 'QUALTRICS' | 'TYPEFORM' | 'SURVEY MONKEY'


