/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ProductsGetById404ResponseErrors } from './products-get-by-id404-response-errors';

/**
 * 
 * @export
 * @interface ProductsGetById404Response
 */
export interface ProductsGetById404Response {
    /**
     * 
     * @type {ProductsGetById404ResponseErrors}
     * @memberof ProductsGetById404Response
     */
    'errors': ProductsGetById404ResponseErrors;
}

