/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProductSkusInner
 */
export interface ProductSkusInner {
    /**
     * Minimal denomination that this product supports (in the product\'s currency)
     * @type {number}
     * @memberof ProductSkusInner
     */
    'min': number;
    /**
     * Maximum denomination that this product supports (in the product\'s currency)
     * @type {number}
     * @memberof ProductSkusInner
     */
    'max': number;
}

