/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RewardsListAllRewards401ResponseErrors } from './rewards-list-all-rewards401-response-errors';

/**
 * 
 * @export
 * @interface RewardsListAllRewards401Response
 */
export interface RewardsListAllRewards401Response {
    /**
     * 
     * @type {RewardsListAllRewards401ResponseErrors}
     * @memberof RewardsListAllRewards401Response
     */
    'errors': RewardsListAllRewards401ResponseErrors;
}

