/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RewardsGetSingleRewardResponseRewardCustomFieldsInner } from './rewards-get-single-reward-response-reward-custom-fields-inner';
import { RewardsGetSingleRewardResponseRewardRecipient } from './rewards-get-single-reward-response-reward-recipient';
import { RewardsGetSingleRewardResponseRewardValue } from './rewards-get-single-reward-response-reward-value';
import { RewardsListAllRewardsResponseRewardsInnerDelivery } from './rewards-list-all-rewards-response-rewards-inner-delivery';

/**
 * A single reward, sent to a recipient. A reward is always part of an order.  Either `products` or `campaign_id` must be specified. 
 * @export
 * @interface RewardsGetSingleRewardResponseReward
 */
export interface RewardsGetSingleRewardResponseReward {
    /**
     * Tremendous ID of the reward
     * @type {string}
     * @memberof RewardsGetSingleRewardResponseReward
     */
    'id'?: string;
    /**
     * Tremendous ID of the order this reward is part of.
     * @type {string}
     * @memberof RewardsGetSingleRewardResponseReward
     */
    'order_id'?: string;
    /**
     * Date the reward was created
     * @type {string}
     * @memberof RewardsGetSingleRewardResponseReward
     */
    'created_at'?: string;
    /**
     * 
     * @type {RewardsGetSingleRewardResponseRewardValue}
     * @memberof RewardsGetSingleRewardResponseReward
     */
    'value'?: RewardsGetSingleRewardResponseRewardValue;
    /**
     * 
     * @type {RewardsGetSingleRewardResponseRewardRecipient}
     * @memberof RewardsGetSingleRewardResponseReward
     */
    'recipient'?: RewardsGetSingleRewardResponseRewardRecipient;
    /**
     * Timestamp of reward delivery within the next year. Note that if date-time is provided, the time values will be ignored.
     * @type {string}
     * @memberof RewardsGetSingleRewardResponseReward
     */
    'deliver_at'?: string;
    /**
     * 
     * @type {Array<RewardsGetSingleRewardResponseRewardCustomFieldsInner>}
     * @memberof RewardsGetSingleRewardResponseReward
     */
    'custom_fields'?: Array<RewardsGetSingleRewardResponseRewardCustomFieldsInner>;
    /**
     * 
     * @type {RewardsListAllRewardsResponseRewardsInnerDelivery}
     * @memberof RewardsGetSingleRewardResponseReward
     */
    'delivery'?: RewardsListAllRewardsResponseRewardsInnerDelivery;
}

