/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RewardsListAllRewardsResponseRewardsInnerCustomFieldsInner } from './rewards-list-all-rewards-response-rewards-inner-custom-fields-inner';
import { RewardsListAllRewardsResponseRewardsInnerDelivery } from './rewards-list-all-rewards-response-rewards-inner-delivery';
import { RewardsListAllRewardsResponseRewardsInnerRecipient } from './rewards-list-all-rewards-response-rewards-inner-recipient';
import { RewardsListAllRewardsResponseRewardsInnerValue } from './rewards-list-all-rewards-response-rewards-inner-value';

/**
 * A single reward, sent to a recipient. A reward is always part of an order.  Either `products` or `campaign_id` must be specified. 
 * @export
 * @interface RewardsListAllRewardsResponseRewardsInner
 */
export interface RewardsListAllRewardsResponseRewardsInner {
    /**
     * Tremendous ID of the reward
     * @type {string}
     * @memberof RewardsListAllRewardsResponseRewardsInner
     */
    'id'?: string;
    /**
     * Tremendous ID of the order this reward is part of.
     * @type {string}
     * @memberof RewardsListAllRewardsResponseRewardsInner
     */
    'order_id'?: string;
    /**
     * Date the reward was created
     * @type {string}
     * @memberof RewardsListAllRewardsResponseRewardsInner
     */
    'created_at'?: string;
    /**
     * 
     * @type {RewardsListAllRewardsResponseRewardsInnerValue}
     * @memberof RewardsListAllRewardsResponseRewardsInner
     */
    'value'?: RewardsListAllRewardsResponseRewardsInnerValue;
    /**
     * 
     * @type {RewardsListAllRewardsResponseRewardsInnerRecipient}
     * @memberof RewardsListAllRewardsResponseRewardsInner
     */
    'recipient'?: RewardsListAllRewardsResponseRewardsInnerRecipient;
    /**
     * Timestamp of reward delivery within the next year. Note that if date-time is provided, the time values will be ignored.
     * @type {string}
     * @memberof RewardsListAllRewardsResponseRewardsInner
     */
    'deliver_at'?: string;
    /**
     * 
     * @type {Array<RewardsListAllRewardsResponseRewardsInnerCustomFieldsInner>}
     * @memberof RewardsListAllRewardsResponseRewardsInner
     */
    'custom_fields'?: Array<RewardsListAllRewardsResponseRewardsInnerCustomFieldsInner>;
    /**
     * 
     * @type {RewardsListAllRewardsResponseRewardsInnerDelivery}
     * @memberof RewardsListAllRewardsResponseRewardsInner
     */
    'delivery'?: RewardsListAllRewardsResponseRewardsInnerDelivery;
}

