/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RewardsResendRewardById404ResponseErrors } from './rewards-resend-reward-by-id404-response-errors';

/**
 * 
 * @export
 * @interface RewardsResendRewardById404Response
 */
export interface RewardsResendRewardById404Response {
    /**
     * 
     * @type {RewardsResendRewardById404ResponseErrors}
     * @memberof RewardsResendRewardById404Response
     */
    'errors': RewardsResendRewardById404ResponseErrors;
}

