/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RewardsGenerateEmbedToken500ResponseErrors } from './rewards-generate-embed-token500-response-errors';

/**
 * 
 * @export
 * @interface RewardsGenerateEmbedToken500Response
 */
export interface RewardsGenerateEmbedToken500Response {
    /**
     * 
     * @type {RewardsGenerateEmbedToken500ResponseErrors}
     * @memberof RewardsGenerateEmbedToken500Response
     */
    'errors': RewardsGenerateEmbedToken500ResponseErrors;
}

