/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RewardsListAllRewardsResponseRewardsInner } from './rewards-list-all-rewards-response-rewards-inner';

/**
 * 
 * @export
 * @interface RewardsListAllRewardsResponse
 */
export interface RewardsListAllRewardsResponse {
    /**
     * 
     * @type {Array<RewardsListAllRewardsResponseRewardsInner>}
     * @memberof RewardsListAllRewardsResponse
     */
    'rewards'?: Array<RewardsListAllRewardsResponseRewardsInner>;
    /**
     * The total number of rewards across all pages
     * @type {number}
     * @memberof RewardsListAllRewardsResponse
     */
    'total_count'?: number;
}

