/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RewardsGenerateEmbedToken429ResponseErrors } from './rewards-generate-embed-token429-response-errors';

/**
 * 
 * @export
 * @interface RewardsGenerateEmbedToken429Response
 */
export interface RewardsGenerateEmbedToken429Response {
    /**
     * 
     * @type {RewardsGenerateEmbedToken429ResponseErrors}
     * @memberof RewardsGenerateEmbedToken429Response
     */
    'errors': RewardsGenerateEmbedToken429ResponseErrors;
}

