/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The redemption token for a reward.
 * @export
 * @interface RewardsGenerateEmbedTokenResponseReward
 */
export interface RewardsGenerateEmbedTokenResponseReward {
    /**
     * Tremendous ID of the reward
     * @type {string}
     * @memberof RewardsGenerateEmbedTokenResponseReward
     */
    'id'?: string;
    /**
     * The token to redeem the reward. 
     * @type {string}
     * @memberof RewardsGenerateEmbedTokenResponseReward
     */
    'token'?: string;
    /**
     * Date the token expires
     * @type {string}
     * @memberof RewardsGenerateEmbedTokenResponseReward
     */
    'expires_at'?: string;
}

