/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RewardCustomFieldsInner } from './reward-custom-fields-inner';
import { RewardRecipient } from './reward-recipient';
import { RewardValue } from './reward-value';
import { RewardWithoutLinkDelivery } from './reward-without-link-delivery';

/**
 * A single reward, sent to a recipient. A reward is always part of an order.  Either `products` or `campaign_id` must be specified. 
 * @export
 * @interface Reward
 */
export interface Reward {
    /**
     * Tremendous ID of the reward
     * @type {string}
     * @memberof Reward
     */
    'id'?: string;
    /**
     * Tremendous ID of the order this reward is part of.
     * @type {string}
     * @memberof Reward
     */
    'order_id'?: string;
    /**
     * Date the reward was created
     * @type {string}
     * @memberof Reward
     */
    'created_at'?: string;
    /**
     * ID of the campaign in your account, that defines the available products (different gift cards, charity, etc.) that the recipient can choose from. 
     * @type {string}
     * @memberof Reward
     */
    'campaign_id'?: string | null;
    /**
     * List of IDs of product (different gift cards, charity, etc.) that will be available to the recipient to choose from.  Providing a `products` array will override the products made available by the campaign specified using the `campaign_id` property unless the `products` array is empty. It will _not_ override other campaign attributes, like the message and customization of the look and feel. 
     * @type {Array<string>}
     * @memberof Reward
     */
    'products'?: Array<string>;
    /**
     * 
     * @type {RewardValue}
     * @memberof Reward
     */
    'value'?: RewardValue;
    /**
     * 
     * @type {RewardRecipient}
     * @memberof Reward
     */
    'recipient'?: RewardRecipient;
    /**
     * Timestamp of reward delivery within the next year. Note that if date-time is provided, the time values will be ignored.
     * @type {string}
     * @memberof Reward
     */
    'deliver_at'?: string;
    /**
     * 
     * @type {Array<RewardCustomFieldsInner>}
     * @memberof Reward
     */
    'custom_fields'?: Array<RewardCustomFieldsInner>;
    /**
     * 
     * @type {RewardWithoutLinkDelivery}
     * @memberof Reward
     */
    'delivery'?: RewardWithoutLinkDelivery;
}

