/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { WebhooksGetDetails401ResponseErrors } from './webhooks-get-details401-response-errors';

/**
 * 
 * @export
 * @interface WebhooksGetDetails401Response
 */
export interface WebhooksGetDetails401Response {
    /**
     * 
     * @type {WebhooksGetDetails401ResponseErrors}
     * @memberof WebhooksGetDetails401Response
     */
    'errors': WebhooksGetDetails401ResponseErrors;
}

