/*
API Endpoints

Deliver monetary rewards and incentives to employees, customers, survey participants, and more through the Tremendous API. For organizational tasks, like managing your organization and it's members within Tremendous, please see the Tremendous Organizational API.

The version of the OpenAPI document: 2
Contact: developers@tremendous.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface WebhooksTriggerEventRequest
 */
export interface WebhooksTriggerEventRequest {
    /**
     * The event to test. See the [List events endpoint reference](https://developers.tremendous.com/) for all available events.
     * @type {string}
     * @memberof WebhooksTriggerEventRequest
     */
    'event': string;
}

